# Generated by Django 5.0.6 on 2024-07-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MealRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("breakfast", models.TextField(blank=True, null=True)),
                ("lunch", models.TextField(blank=True, null=True)),
                ("dinner", models.TextField(blank=True, null=True)),
                ("snack", models.TextField(blank=True, null=True)),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
